"""Workflow DAG execution APIs."""

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.database import get_db
from app.schemas.common import Result
from app.schemas.workflow import WorkflowExecuteRequest
from app.services.workflow_executor_service import workflow_executor_service

router = APIRouter()


@router.post("/execute", response_model=Result)
def execute_workflow(
    data: WorkflowExecuteRequest,
    db: Session = Depends(get_db),
):
    """Execute a DAG generated by dam-workflow."""
    result = workflow_executor_service.execute(
        db,
        dag=data.dag,
        prompt=data.prompt,
        images=data.images,
        videos=data.videos,
        media_objects=data.media_objects,
        sensor_data=data.sensor_data,
        event_type=data.event_type,
        media_mode=data.media_mode,
        max_frames=data.max_frames,
        frame_interval_seconds=data.frame_interval_seconds,
        fallback_to_frames=data.fallback_to_frames,
        mode=data.mode,
        validate=data.validate,
        filter_output=data.filter_output,
        wait_timeout=data.wait_timeout,
    )
    return Result(code=200, data=result)
