services:
  yolo26x-smallobj-2-api:
    build: .
    image: yolo-od:latest
    container_name: yolo26x-smallobj-2-detector
    restart: unless-stopped
    ports:
      - "8012:8000"
    environment:
      - MINIO_ENDPOINT=172.17.0.1:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MODEL_WEIGHTS=/app/models/yolo26x_smallobj_2_best.pt
      - CLASS_NAMES=boat,swimmer,person,crowd
      - DEVICE=0
      - IMG_SIZE=960
      - CONF=0.25
      - IOU=0.45
      - SAVE_ANNOTATED=true
    volumes:
      - ./yolo26x_smallobj_2_best.pt:/app/models/yolo26x_smallobj_2_best.pt:ro
    networks:
      - box_system_default

networks:
  box_system_default:
    external: true
