"""Workflow execution request schemas."""

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


class WorkflowExecuteRequest(BaseModel):
    """Execute a generated workflow DAG."""

    dag: Dict[str, Any] = Field(..., description="DAG generated by dam-workflow")
    prompt: str = Field("", description="Original event prompt")
    images: List[str] = Field(default_factory=list, description="Image object paths or URLs")
    videos: List[str] = Field(default_factory=list, description="Video object paths or URLs")
    media_objects: List[Dict[str, Any]] = Field(default_factory=list, description="Typed media object references")
    sensor_data: Dict[str, Any] = Field(default_factory=dict, description="Sensor/event data")
    event_type: Optional[str] = Field(None, description="Resolved DAM event type")
    mode: Literal["infer", "run"] = Field(
        "infer",
        description="infer requires running models; run auto-starts/stops models",
    )
    validate: bool = Field(False, description="Validate node inputs with model IO schema")
    filter_output: bool = Field(False, description="Filter node outputs with model IO schema")
    wait_timeout: int = Field(600, description="Model readiness timeout for run mode")
