services:
  mobilenetv4-cls-api:
    build: .
    container_name: mobilenetv4-classifier
    restart: unless-stopped
    ports:
      - "8006:8000"
    environment:
      - MINIO_ENDPOINT=172.17.0.1:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MODEL_WEIGHTS=/app/models/mobilenetv4_conv_medium_cls_acc_92_25.pt
      - MODEL_BACKEND=timm
      - MODEL_NAME=mobilenetv4_conv_medium.e500_r256_in1k
      - CLASS_NAMES=earthquake,flood,landslide,mudslide
      - DEVICE=0
      - IMG_SIZE=256
      - TOP_K=3
    volumes:
      - ./mobilenetv4_conv_medium_cls_acc_92_25.pt:/app/models/mobilenetv4_conv_medium_cls_acc_92_25.pt:ro
    networks:
      - box_system_default

networks:
  box_system_default:
    external: true
