"""Qwen3.5-35B 云端增强推理代理服务。"""

import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Any, Dict
import httpx

app = FastAPI(
    title="Qwen3.5-35B 云端增强推理代理",
    description="转发请求到云端 Cloud API 10.196.85.11:9458",
    version="1.0.0",
)

CLOUD_URL = os.getenv("CLOUD_URL", "http://10.196.85.11:9458")
INFERENCE_PATH = os.getenv("INFERENCE_PATH", "/infer")

client = httpx.Client(timeout=300.0)


class InferRequest(BaseModel):
    """推理请求（透传）。"""
    task_id: str = None
    media_objects: list = None
    specialized_result: Dict[str, Any] = None
    sensor_data: Dict[str, Any] = None
    edge_analysis: Dict[str, Any] = None
    report_requirement: Dict[str, Any] = None

    class Config:
        extra = "allow"


MEDIA_KEYS = (
    "images",
    "image_paths",
    "image_urls",
    "videos",
    "video_paths",
    "video_urls",
    "media_objects",
    "media",
)


def _as_dict(value: Any) -> dict:
    return value if isinstance(value, dict) else {}


def _find_cloud_media_objects(value: Any) -> list | None:
    """Find cloud MinIO media references generated by the edge 4B wrapper."""
    if isinstance(value, dict):
        cloud_media = value.get("cloud_media_objects")
        if isinstance(cloud_media, list) and cloud_media:
            return cloud_media
        for item in value.values():
            found = _find_cloud_media_objects(item)
            if found:
                return found
    elif isinstance(value, list):
        for item in value:
            found = _find_cloud_media_objects(item)
            if found:
                return found
    return None


def _strip_media_refs(value: Any) -> Any:
    if not isinstance(value, dict):
        return value
    cleaned = dict(value)
    for key in MEDIA_KEYS:
        cleaned.pop(key, None)
    return cleaned


def _normalize_workflow_payload(payload: dict) -> dict:
    """Prefer cloud MinIO objects over edge-local MinIO URLs for cloud inference."""
    normalized = dict(payload)
    cloud_media = _find_cloud_media_objects(normalized)
    if not cloud_media:
        return normalized

    normalized["media_objects"] = cloud_media
    normalized["images"] = []
    normalized["videos"] = []
    normalized["strict_media"] = True

    inputs = _as_dict(normalized.get("inputs"))
    if inputs:
        inputs = _strip_media_refs(inputs)
        inputs["media_objects"] = cloud_media
        inputs["cloud_media_objects"] = cloud_media
        normalized["inputs"] = inputs

    sensor_data = _as_dict(normalized.get("sensor_data"))
    if sensor_data:
        normalized["sensor_data"] = _strip_media_refs(sensor_data)

    return normalized


def _cloud_error_detail(resp: httpx.Response) -> str:
    try:
        body = resp.json()
    except Exception:
        body = resp.text
    text = str(body)
    if len(text) > 1200:
        text = f"{text[:1200]}..."
    return f"云端返回错误: {resp.status_code}; detail={text}"


@app.get("/health")
async def health():
    """健康检查。"""
    try:
        resp = client.get(f"{CLOUD_URL}/health", timeout=5)
        if resp.status_code < 400:
            return {"status": "healthy", "cloud": "reachable"}
    except Exception:
        pass
    return {"status": "healthy", "cloud": "unreachable"}


@app.post("/api/v1/cloud-inference")
async def infer(request: InferRequest):
    """转发推理请求到云端。"""
    try:
        payload = _normalize_workflow_payload(request.model_dump(exclude_none=True))
        resp = client.post(
            f"{CLOUD_URL}{INFERENCE_PATH}",
            json=payload,
        )
        resp.raise_for_status()
        return resp.json()
    except httpx.ConnectError:
        raise HTTPException(status_code=502, detail="云端服务不可达")
    except httpx.HTTPStatusError as e:
        raise HTTPException(status_code=502, detail=_cloud_error_detail(e.response))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/infer")
@app.post("/predict")
async def workflow_infer(request: InferRequest):
    """统一 DAG 工作流入口，透传 prompt、视频路径、上游结果给云端服务。"""
    try:
        payload = _normalize_workflow_payload(request.model_dump(exclude_none=True))
        if "report_requirement" not in payload:
            payload["report_requirement"] = {
                "format": "dam_workflow",
                "require_fields": [
                    "report",
                    "risk_level",
                    "recommendations",
                    "detailed_scene_analysis",
                    "risk_reasoning",
                    "impact_assessment",
                    "response_plan",
                    "monitoring_suggestions",
                    "template_data",
                ],
            }
        resp = client.post(
            f"{CLOUD_URL}{INFERENCE_PATH}",
            json=payload,
        )
        resp.raise_for_status()
        data = resp.json()
        report = (
            data.get("report")
            or data.get("response")
            or data.get("analysis_report")
            or data.get("result")
            or ""
        )
        return {
            **data,
            "status": data.get("status", "success"),
            "response": data.get("response") or report,
            "report": report,
            "risk_level": data.get("risk_level", "unknown"),
        }
    except httpx.ConnectError:
        raise HTTPException(status_code=502, detail="云端服务不可达")
    except httpx.HTTPStatusError as e:
        raise HTTPException(status_code=502, detail=_cloud_error_detail(e.response))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=9457)
